### ISSUE TITLE
PROBA-V reader: wrong interpretation of status map band values of S1/S10 products

### ISSUE THREAD

**Issue by dirkdaems** [senbox-org/s3tbx#7]
The PROBA-V reader interprets the status map band (SM_FLAGS) values of S1/S10 products incorrect. E.g. for product PROBAV_S1_TOC_X11Y11_20150521_1KM_V001.HDF5 it shows values larger than 255 which is impossible according to the product manual (http://www.vito-eodata.be/PDF/image/PROBAV-Products_User_Manual.pdf):
![snap](https://cloud.githubusercontent.com/assets/6524675/14554328/8c7c8676-02ec-11e6-8bf0-891bec8d8576.png)

**Comment by marpet** [comment]
Thanks for your report.
Since Proba-V uses more than one bit to encode a single flag we had to work around this. Multiple bits per flag is currently not supported by SNAP. (I've noted this [in our issue tracker](https://senbox.atlassian.net/browse/SNAP-468)).
The values shown for the SM_FLAGS band are not in line with the user guide but the flagging is correct.The original values are just mapped to new values.
When you open in the Product Explorer SM_FLAGS in the group Flag Codings you will see each flag with its associated value.
